import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <div className="container">
        9801433555
        </div>
      
      
      <div className="container">
        <img className="w-100"src="https://www.digitalsahuji.com/storage/app/public/company/2023-06-27-649a72e48c94a.png"></img>
      </div>
        
        {children}</body>
    </html>
  );
}
