import { Inter } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className="bg-[pink] p-5">
          <div className="container flex justify-between mx-auto">
            <h1>Logo</h1>
          <h2>sandhya@gmail.com</h2>
          </div>
        </header>
        <nav className="bg-green-200  p-5">
          <ul className="flex justify-center gap-7">
            <li><Link href="/">Home</Link></li>
            <li><Link href="/about">About</Link></li>
            <li><Link href="/blog">Blog</Link></li>
            <li><Link href="/contact">Contact</Link></li>
            
          </ul>
        </nav>
        
        {children}</body>
        <footer className="bg-slate-500">
          <ul className="text-center text-white">
            <li><Link href="">@copyright</Link></li>
          </ul>
        </footer>
    </html>
  );
}
